apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: tap13
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  portal:
    title: Tanzu Application Platform Demos
    password: test
    registration:
      type: anonymous
      enabled: true
    updates:
      workshop: true
    sessions:
      maximum: 45
  workshops:
    - name: tap13-dev
      expires: 360m
      orphaned: 120m
      capacity: 5
      reserved: 2
    - name: tap13-opr
      expires: 360m
      orphaned: 120m
      capacity: 5
      reserved: 1
